resources:
- name: git
  type: git
  source:
    private_key: ((github.private_key))
    uri: git@github.com:springernature/halfpipe-cf-plugin.git

- name: version
  type: semver
  source:
    branch: version
    driver: git
    file: version
    private_key: ((github.private_key))
    uri: git@github.com:springernature/halfpipe-cf-plugin.git

- name: release
  type: github-release
  source:
    access_token: ((api-keys.halfpipe-cli))
    owner: springernature
    repository: halfpipe-cf-plugin

jobs:
- name: Test, build and release
  serial: true
  plan:
  - get: git
    trigger: true
  - task: Test and build
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: golang
          tag: golang:1.11-stretch
      run:
        path: /bin/sh
        args:
        - -ec
        - |
          export CONCOURSE_ROOT=$PWD
          export ARTIFACTS=$PWD/artifacts
          cd git

          echo go test
          go test -cover ./...

          echo
          echo Integration Test
          TMPDIR=`mktemp -d`
          export PATH=$PATH:$TMPDIR
          CF_TAR_URL="https://packages.cloudfoundry.org/stable?release=linux64-binary&version=6.35.0&source=github-rel"
          PLUGIN_BIN_PATH=${TMPDIR}/plugin

          wget -qO- ${CF_TAR_URL} | tar xvz -C $TMPDIR > /dev/null

          # Compile the plugin
          go build -o ${PLUGIN_BIN_PATH} cmd/plugin.go > /dev/null

          CF_HOME=${TMPDIR} cf install-plugin ${PLUGIN_BIN_PATH} -f

          echo
          echo Building plugin for all platforms
          CGO_ENABLED=0 GOARCH=amd64 GOOS=darwin go build -ldflags "-X github.com/springernature/halfpipe-cf-plugin/config.SHA=`cat .git/ref`" -o $ARTIFACTS/halfpipe_cf_plugin_darwin cmd/plugin.go
          CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -ldflags "-X github.com/springernature/halfpipe-cf-plugin/config.SHA=`cat .git/ref`" -o $ARTIFACTS/halfpipe_cf_plugin_linux cmd/plugin.go
          CGO_ENABLED=0 GOARCH=amd64 GOOS=windows go build -ldflags "-X github.com/springernature/halfpipe-cf-plugin/config.SHA=`cat .git/ref`" -o $ARTIFACTS/halfpipe_cf_plugin_windows.exe cmd/plugin.go
      inputs:
      - name: git
      outputs:
      - name: artifacts
  - put: version
    params:
      bump: minor
  - put: release
    params:
      globs:
        - artifacts/halfpipe_cf_plugin_*
      name: git/.name
      tag: version/version
