jobs:
- name: Test, build and release
  plan:
  - get: git
    trigger: true
  - config:
      container_limits: {}
      image_resource:
        source:
          repository: golang
          tag: 1.11-stretch
        type: docker-image
      inputs:
      - name: git
      outputs:
      - name: artifacts
      platform: linux
      run:
        args:
        - -ec
        - |
          export CONCOURSE_ROOT=$PWD
          export ARTIFACTS=$PWD/artifacts
          cd git

          echo go test
          go test -cover ./...

          echo
          echo Integration Test
          TMPDIR=`mktemp -d`
          export PATH=$PATH:$TMPDIR
          CF_TAR_URL="https://packages.cloudfoundry.org/stable?release=linux64-binary&version=6.35.0&source=github-rel"
          PLUGIN_BIN_PATH=${TMPDIR}/plugin

          wget -qO- ${CF_TAR_URL} | tar xvz -C $TMPDIR > /dev/null

          # Compile the plugin
          go build -o ${PLUGIN_BIN_PATH} cmd/plugin.go > /dev/null

          CF_HOME=${TMPDIR} cf install-plugin ${PLUGIN_BIN_PATH} -f

          echo
          echo Building plugin for all platforms
          CGO_ENABLED=0 GOARCH=amd64 GOOS=darwin go build -ldflags "-X github.com/springernature/halfpipe-cf-plugin/config.SHA=`cat .git/ref`" -o $ARTIFACTS/halfpipe_cf_plugin_darwin cmd/plugin.go
          CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -ldflags "-X github.com/springernature/halfpipe-cf-plugin/config.SHA=`cat .git/ref`" -o $ARTIFACTS/halfpipe_cf_plugin_linux cmd/plugin.go
          CGO_ENABLED=0 GOARCH=amd64 GOOS=windows go build -ldflags "-X github.com/springernature/halfpipe-cf-plugin/config.SHA=`cat .git/ref`" -o $ARTIFACTS/halfpipe_cf_plugin_windows.exe cmd/plugin.go
        path: /bin/sh
    task: Test and build
  - params:
      bump: minor
    put: version
  - params:
      globs:
      - artifacts/halfpipe_cf_plugin_*
      name: git/.name
      tag: version/version
    put: release
  serial: true
resources:
- name: git
  source:
    private_key: ((halfpipe-github.private_key))
    uri: git@github.com:springernature/halfpipe-cf-plugin.git
  type: git
  check_every: 24h
- name: release
  source:
    access_token: ((api-keys.halfpipe-cli))
    owner: springernature
    repository: halfpipe-cf-plugin
  type: github-release
  check_every: 24h
- name: version
  source:
    branch: version
    driver: git
    file: version
    private_key: ((halfpipe-github.private_key))
    uri: git@github.com:springernature/halfpipe-cf-plugin.git
  type: semver
  check_every: 24h
