resource_types:
- name: cf-resource
  type: docker-image
  source:
    repository: platformengineering/cf-resource
    tag: dev

resources:
- name: git
  type: git
  source:
    private_key: ((github.private_key))
    uri: git@github.com:springernature/halfpipe-cf-plugin.git

- name: docker-registry-image-stable
  type: docker-image
  source:
    password: ((docker-hub-pe.password))
    repository: platformengineering/cf-resource
    username: platformengineering
    tag: stable

- name: docker-registry-image-dev
  type: docker-image
  source:
    password: ((docker-hub-pe.password))
    repository: platformengineering/cf-resource
    username: platformengineering
    tag: dev

- name: cf
  type: cf-resource
  check_every: 5s
  source:
    api: ((cloudfoundry.api-gcp))
    org: engineering-enablement
    password: ((cloudfoundry.password))
    space: integration_test
    username: ((cloudfoundry.username))

jobs:
- name: run test.sh
  serial: true
  plan:
  - get: git
    trigger: true
  - task: run
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: golang
          tag: 1.10.0-alpine3.7
      params:
        RUNNING_IN_CI: "true"
      run:
        path: /bin/sh
        args:
        - -ec
        - ./test.sh
        dir: git
      inputs:
      - name: git

- name: Push dev docker image
  serial: true
  plan:
  - get: git
    passed:
    - run test.sh
    trigger: true
  - put: docker-registry-image-dev
    params:
      build: git
      tag: git/.docker-dev-tag

- name: Test resource
  serial: true
  plan:
  - get: git
    passed:
    - Push dev docker image
  - get: docker-registry-image-dev
    passed:
    - Push dev docker image
    trigger: true
  - put: cf
    params:
      appPath: git/.integration_test
      command: halfpipe-push
      gitRefPath: git/.git/ref
      manifestPath: git/.integration_test/manifest.yml
      testDomain: apps.public.gcp.springernature.io
  - put: cf
    params:
      appPath: git/.integration_test
      command: halfpipe-promote
      gitRefPath: git/.git/ref
      manifestPath: git/.integration_test/manifest.yml
      testDomain: apps.public.gcp.springernature.io
  ensure:
    put: cf
    params:
      appPath: git/.integration_test
      command: halfpipe-cleanup
      gitRefPath: git/.git/ref
      manifestPath: git/.integration_test/manifest.yml
      testDomain: apps.public.gcp.springernature.io

- name: Tag docker image as stable
  serial: true
  plan:
  - get: git
    passed:
    - Test resource
    trigger: true
  - put: docker-registry-image-stable
    params:
      build: git
      tag: git/.docker-stable-tag
